Repository MetaCell/cloud-harness, pull requests merged in 2022-01, with the labels that each got.

#364 Feature/361: stop using the admin account for api calls to KC
  applications/accounts/Dockerfile
  applications/accounts/deploy/templates/api-user-secret.yaml
  applications/accounts/scripts/create_api_user.sh
  libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
  utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml
Labels: alert:deployment

#377 #347 add test coverage for values.yaml precedence
  .gitignore
  utilities/tests/resources/applications/events/deploy/values-prod.yaml
  utilities/tests/resources/applications/events/deploy/values.yaml
  utilities/tests/test_helm.py
Labels: testing

#376 #263 chore fix -e parameter description
  utilities/harness-deployment
Labels: chore
